---
title: "Cheryl KOUADIO"
---

<div class="box">
Ce site web a été conçu et généré à l'aide de Quarto, dans le but principal d'offrir un soutien aux étudiants de l'ENSAI qui pourraient se trouver face à des défis similaires à ceux que j'ai rencontrés au cours de mon parcours académique, notamment durant mes 2ème et 3ème années d'étude.
L'intention derrière la création de ce site n'est pas de remplacer les enseignements prodigués par nos estimés professeurs. Au contraire, il vise à compléter leur travail remarquable en partageant mes expériences personnelles et les projets que j'ai réalisés. L'objectif est de fournir une ressource supplémentaire qui peut aider les étudiants à naviguer dans leurs propres projets et défis académiques.
</div>

# Théorie des valeurs extrêmes
- Résumé de la théorie des valeurs extrêmes ([EVT_resume.pdf](3A/EVT/EVT_resume.pdf){.external target="_blank"})


# Microéconometrie appliquée
- Résumé des méthodes de microéconométrie appliquée enseignée à la promo 2024-2025 Ensai ([applied_micro.pdf](2A/Courses.pdf){.external target="_blank"})

# Apprentissage supervisée
## Régressions

- Regression linéaire ([regression_lin.qmd](2A/App_sup/reg_lin.qmd){.external target="_blank"})

## Classifications

- Applications des arbres & forêts aléatoires sur un jeu de données ([arbres_&_forets_aleatoires.html](2A/App_sup/arbres_&_forets_aleatoires.html){.external target="_blank"}) </li>
