---
title: "Cheryl KOUADIO"
---

# Gestion des risques


::: {.callout-note}
Compte tenu de ma spécialisation en gestion des risques, les contenus que je prévois de partager dans cette section dédiée à la 3ème année (3A) porteront principalement sur les enseignements spécifiques à cette spécialisation. Je m'efforcerai de rendre ces partages aussi pertinents et enrichissants que possible, en espérant qu'ils serviront de guide précieux pour ceux qui suivront une voie similaire.
:::


### Analyse financière
::: {.blog-section}
- [Construction du bilan d'entreprise](3A/bilan_entreprise.qmd)
- [Reglementation prudentielle  **TO REWRITE**](3A/reglementation_prudentielle.qmd)
:::

### Risques financiers
::: {.blog-section}
- [Définition du risque financier](3A/risque_def.qmd)
- [Value-at-risk (VaR)](3A/value-at-risk/var_def.qmd) :
    - [Définition de la VaR](3A/value-at-risk/var_def.qmd)
    - [Implémentation de la VaR sur python](3A/value-at-risk/var_application.qmd)
    - [TP1 : Méthodes traditionnelles de calcul de la VaR et Expected Shortfall (ES)](3A/value-at-risk/var_classiques.qmd)
    - [TP2 : Méthodes basées sur la théorie des valeurs extrêmes](3A/value-at-risk/var_evt.qmd)
    - [TP3 : Méthodes d'une calcul d'une VaR dynamique (basé sur GARCH)](3A/value-at-risk/var_garch.qmd)
    - [Estimation de la CreditVaR à l'aide de la théorie des copules](3A/value-at-risk/pj_copules.qmd)
:::

### Scoring
::: {.blog-section}
::: 

### Calibrations de processus stochastique
::: {.blog-section}
- [Calibration avec le modèle de black-scholes](3A/proc_stochastique/modele_bs.qmd)
- [Calibration du modèle à volatilité stochastique de Taylor - Filtre de Kalman](3A/proc_stochastique/modele_log_sv-part1.qmd)
- [Calibration du modèle à volatilité stochastique de Taylor - Filtre particulaire bootstrap](3A/proc_stochastique/modele_log_sv-part2.qmd)
- [Modèle de Heston](3A/proc_stochastique/modele_heston.qmd) :
    - [Estimation de la volatilité avec le filtre boostrap](3A/proc_stochastique/modele_heston.qmd)
    - [Comparaison du filtre bootstrap au filtre particulaire auxiliaire (APF)](3A/proc_stochastique/APF_filter.qmd)
- [Courbes de taux (Construction d'une courbe ZC, Modèle Hull - White)](3A/proc_stochastique/pj_courbe_tx.qmd)

:::

### Gestion de portefeuille et pricing
::: {.blog-section}
- [Gestion de risques d'un portefeuille d'actifs](3A/gestion_actifs/mesures_rsq.qmd)
- [Profil d'écoulement de portefeuille](3A/gestion_actifs/profil_liquid.qmd)
- [Valorisation d'obligation + risque de taux](3A/gestion_actifs/bond_valo.qmd)
- [Pricing d'options vanilles  **TO DO**]()
- [Pricing de taux, swap, d'obligations  **TO DO**]()
- [Tracking error  **TO DO**]()
- [Construction de portefeuille markowitz  **TO DO**]()
:::

### Autres sujets 
::: {.blog-section}
-   [Investissement socialement responsable](autres/ISR.qmd)
-   [Finance durable](autres/finance_durable.qmd)
-   [Corrélation de spearman vs Corrélation de pearson](autres/spearman-pearson.qmd)
:::

## Projets et applications déployées
::: {.blog-section}

**Projets**

- [Projet de séries temporelles](3A/rapports/rapport_series_temporelles.pdf)
- [Projet de scoring **TO DO**]()
- [Projet de théorie de valeurs extrêmes 1](3A/rapports/projet_EVT_Kouadio_Kougoum_Ouyassin.pdf)
- [Projet de théorie de valeurs extrêmes 2](3A/rapports/projet_EVT_Wane_Kouadio.pdf)

**Applications déployées**

- [Stock price prediction : CAC40](https://cac40forecast.streamlit.app/)
- [Asset pricing and management](https://github.com/Niyo-D-JC/Asset-Pricing-and-Management)
:::