---
title: "La réglementation prudentielle"
author: "Cheryl Kouadio"
sidebar: auto
date: "2024-07-01"
---

# TO REWRITE

La réglementation prudentielle a été initiée par le développement des marchés financiers et des chocs alimentés par diverses crises financières. Face à ce constat, les autorités de contrôle bancaire ainsi que les autorités de marché ont pris des décisions pour réguler les marchés. C'est notamment le rôle qu'occupe le Comité de Bâle ou la Commission bancaire, qui ont pour objectif de renforcer la stabilité des marchés financiers. En France, l'ACPR (Autorité de Contrôle Prudentiel et de Résolution) et la Banque de France sont membres du Comité de Bâle et participent à ses travaux et décisions.

Il existe par ailleurs plusieurs textes réglementaires ou documents relatifs au risque de marché. Parmi ces textes, on peut citer le document de référence pour calculer le ratio de solvabilité de la Commission bancaire, intitulé "[Modalités de calcul et de publication des ratios prudentiels dans le cadre de la CRDIV et exigence de MREL](https://acpr.banque-france.fr/sites/default/files/media/2023/07/17/20230711_notice_college.pdf)", actualisé tous les ans par l'ACPR en France.

# Notion de risque de marché

Le risque de marché est l'un des grands types de risque d'intérêt pour une institution financière. Selon l'ACPR, il recouvre :

-   le risque de change et le risque sur les matières premières qui s’apprécient sur l’ensemble des portefeuilles bancaire et de négociation de l’Établissement assujetti ;

-   le risque de position qui s’apprécie uniquement sur le portefeuille de négociation : risque général et spécifique sur des instruments de créance, sur des actions et instruments assimilés

Par ailleurs, le portefeuille de négociation sert de référence pour le calcul des risques de marché, et fait l'objet d'une définition prudentielle dans le [journal officiel de l'Union Européenne](https://eur-lex.europa.eu/oj/direct-access.html).

L'exigence en fonds propres au titre du risque de marché comprend donc un périmètre large pour le portefeuille de négociation(trading book) mais aussi par le bilan et le hors-bilan comme, par exemple, les risques du portefeuilles d'investissement.

Ces exigences en fonds propres s'appliquent sur une base consolidée. Pour les mesurer, les établissements ont le choix entre deux approches : l'approche standard et l'approche modèle interne (Internal Models Approach).

## Approche standard de mesure du risque de marché

L'approche standard de mesure du risque de marché consiste à calculer les exigences en fonds propres pour chaque catégorie de risque, à savoir :

-   le risque de taux (général et spécifique) calculé sur le périmètre du portefeuille de négociation ;

-   le risque lié aux titres de propriété(général et spécifique) calculé sur le périmètre du portefeuille de négociation ;

-   le risque de change calculé sur l'ensemble des opérations appartenant aussi bien au portefeuille de négociation ou non;

-   le risque sur matières premières calculé sur l'ensemble des opérations du portefeuille de négociation ou non;

-   les risques opérationnels calculés sur les options associées à chachune des catégories de risque citées ci-dessus.

Par la suite, il s'agit de les additionner de manière arithmétique. Par exemple, pour les titres de propriété, l'exigence de fonds propres est la somme de l'exigence de fonds propres pour le risque général et l'exigence de fonds propres pour le risque spécifique.

Pour le calcul des exigences de fonds propres au titre des risques de marché, il faut tout d'abord déterminer les positions nettes. Les positions de titrisation logées dans le portefeuille de négociation sont traitées comme tout instrument de dette au titre du risque de taux.

Pour le risque spécifique, l'exigence en fonds propres sera la somme des positions nettes multipliées par un coefficient de pondération (2%, 4%, 8% ou 12%) choisi en fonction de la liquidité et la diversification de la position. Pour le risque général, l'exigence en fonds propres est la somme des positions nettes globales (pour chaque marché national) multipliées par 8%.

## Approche modèle interne

L'approche modèle interne est une méthode de calcul des exigences en fonds propres pour le risque de marché qui permet aux établissements de calculer leurs propres exigences. L'exigence en fonds propres est généralement un calcul de la VaR. Cette approche est soumise à des conditions strictes et à une validation par l'ACPR.

Concernant l'utilisation conjointe des modèles internes et de l'approche standard, la position de la commission prête une attention particulière à la permanence des méthodes ainsi qu'à leur évolution. L'objectif est de s'orienter vers un modèle global qui tient compte de l'ensemble des risques de marché.

> Ainsi, un établissement commençant à utiliser des modèles pour une ou plusieurs catégories de facteurs de risque doit en principe étendre progressivement ce système à tous ses risques à la méthodologie standardisée (à moins que la Commission Bancaire ne lui ait retiré son agrément pour ses modèles).

Pour une banque, la construction d'un modèle interne doit permettre de fournir une mesure plus économique du risque de marché. Au titre de l'article 363 du CRR (Règlement sur les exigences de fonds propres), l'autorité compétente autorise les établissements assujettis à utiliser leurs modèles internes pour calculer les exigences de fonds propres pour risques de marché, après avoir vérifié qu'ils se conforment bien aux exigences des sections 2, 3 et 4 du chapitre 5 du titre IV de la 3ème partie du CRR [@journal]. L'autorisation d'utiliser des modèles internes accordée par les autorités compétentes est requise pour chaque catégorie de risques (risque général et spécifique liés aux actions et titres de créance, risque de change et risque sur matières premières), et elle n'est accordée que si le modèle interne couvre une part importante des positions d'une certaine catégorie de risque.

Parmi ces exigences, nous notons des exigences qualitatives (article 368), relatives à la mesure du risque (articles 367) mais aussi d'ordre général (article 365).

#### Exigences générales

Le calcul de la valeur en risque visée à l'article 364 est soumis aux exigences suivantes:

a)  un calcul quotidien de la valeur en risque;
b)  un intervalle de confiance, exprimé en centiles et unilatéral, de 99 %;
c)  une période de détention de dix jours;
d)  une période effective d'observation historique d'au moins un an, à moins qu'une période d'observation plus courte ne soit justifiée par une augmentation significative de la volatilité des prix;
e)  des mises à jour au moins mensuelles des séries de données.

L'établissement peut utiliser des mesures de la valeur en risque calculées sur la base de périodes de détention inférieures à dix jours, qu'il porte à dix jours selon une méthode appropriée qu'il revoit régulièrement.

Chaque établissement doit également calculer, au moins hebdomadairement, une "valeur en risque en situation de tensions" (Stressed VaR) pour son portefeuille courant. Cette Stressed VaR doit être calculée conformément aux mêmes exigences que la VaR standard énoncées plus haut (intervalle de confiance de 99% etc.). Cependant, les données d'entrée du modèle de Stressed VaR doivent être calibrées par rapport à une période historique de tensions financières significatives d'au moins 12 mois, pertinente pour le portefeuille de l'établissement. Le choix de cette période de tensions historiques fait l'objet d'un examen au moins annuel par l'établissement, qui en communique les résultats aux autorités compétentes. L'objectif est de s'assurer que la Stressed VaR reflète de manière adéquate les risques auxquels l'établissement serait exposé en période de crise financière.

Pour résumer, les établissements doivent calculer la perte potentielle quotidiennement pour une période de détention de 10 jours, avec un intervalle de confiance de 99%. Ils doivent également calculer une Stressed VaR au moins une fois par semaine, en utilisant des données historiques de périodes de tensions financières significatives.

Notons $VaR(t)$ la valeur en risque à la date $t$ et $sVaR(t)$ la valeur en risque en situation de tensions à la date $t$. Les exigences en fonds propres $FP(t)$ à la date t pour le risque de marché sont calculées comme suit:

$$FP(t)=max(VaR(t-1),m_c \times \frac{1}{60}\sum_{i=1}^{60}VaR(t-i)) + max(sVaR(t-1),m_s \times \frac{1}{60}\sum_{i=1}^{60}sVaR(t-i))$$

où $m_c$ et $m_s$ sont des facteurs multiplicatifs qu'on vera plus tard.

Dans des périodes normales, l'exigence en fonds propres sera donc la somme d'un multiple de la moyenne des valeurs en risque et de la moyenne des valeurs en risque en situation de tensions sur les 60 derniers jours. Ce n'est que dans les périodes de crises financières que l'exigence en fonds propres correspond à la VaR ou à la sVaR du jour précédent.

Chacun des facteurs de multiplication ($m_c$) et ($m_s$) est égal à la somme du chiffre 3, au minimum, et d'un cumulateur compris entre 0 et 1 conformément au tableau 1. Ce cumulateur dépend du nombre de dépassements, sur les 250 derniers jours ouvrés, mis en évidence par les contrôles a posteriori de la mesure de la valeur en risque, au sens de l'article 365, paragraphe 1, effectués par l'établissement.

```{r, echo=FALSE, center=TRUE}
knitr::opts_chunk$set(echo = FALSE,  message=FALSE, warning = FALSE,cache = TRUE)
library(dplyr)
# Création d'un dataframe pour le tableau
donnees <- data.frame(
  `Nombre de dépassements` = c("moins de 5", "5", "6", "7", "8", "9", "10 ou plus"),
  `Cumulateur` = c(0.00, 0.40, 0.50, 0.65, 0.75, 0.85, 1.00)
)

donnees
```

En ce qui concerne le risque spécifique, tout modèle interne utilisé pour calculer les exigences de fonds propres et tout modèle interne utilisé pour la négociation en corrélation satisfont aux exigences supplémentaires suivantes:

a)  le modèle interne explique la variation historique des prix à l'inté rieur du portefeuille;
b)  il reflète la concentration en termes de volume et de modifications de la composition du portefeuille;
c)  il peut supporter un environnement défavorable;
d)  il est validé par des contrôles a posteriori(backtesting) visant à établir si le risque spécifique a été correctement pris en compte. Si l'établissement effectue ces contrôles a posteriori sur la base de sous-portefeuilles pertinents, ces derniers sont choisis de manière cohérente;
e)  il tient compte du risque de base lié à la signature et, en particulier, il est sensible aux différences idiosyncratiques significatives existant entre des positions similaires, mais non identiques;
f)  il tient compte du risque d'événement.

Le risque spécifique vise à tenir compte du risque de contrepartie lié à l'emetteur de l'instrument.

Pour en savoir plus, reportez au [règlement (UE) No 575/2013 du parlement européen](https://eur-lex.europa.eu/legal-content/FR/TXT/PDF/?uri=CELEX:02013R0575-20230628) du journal officiel de l'Union Européenne, appelé aussi règlement CRR. (voir aussi la notice 2020 relative aux « [Modalités de calcul et de publication des ratios prudentiels dans le cadre de la CRDIV](https://acpr.banque-france.fr/sites/default/files/media/2023/07/17/20230711_notice_college.pdf)»).

# Définitions

Portefeuille de négociation[@journal]

:   | (86)"portefeuille de négociation": toutes les positions sur instruments financiers et matières premières détenues par un établissement à des fins de négociation ou dans le but de couvrir d'autres éléments du portefeuille de négociation;

Position nette

:   Pour un individu ou une entreprise, la position nette correspond à la différence entre leurs actifs (avoirs, créances) et leurs passifs (dettes, engagements).

Risque général vs Risque spécifique[@guide2021]

:   Pour l'application du présent titre, le risque de position concernant un titre de créance ou de propriété, ou un instrument dérivé sur un tel titre, est décomposé en deux éléments : a) Le risque général, c'est-à-dire le risque d'une variation de prix provoquée par une fluctuation du niveau des taux d'intérêt, dans le cas de titres de créance ou d'instruments dérivés de tels titres, ou par un mouvement général du marché des actions, dans le cas de titres de propriété ou d'instruments dérivés sur de tels titres ; b) Le risque spécifique, c'est-à-dire le risque d'une variation de prix sous l'influence de facteurs liés à l'émetteur du titre ou de l'instrument sous-jacent. Les titres émis par l'établissement assujetti ne sont pas pris en compte, ni les titres émis par les établissements de crédit régionaux ou centraux affiliés à un même organe central au sens de l'article L. 511-31 du code monétaire et financier.